language: python
python:
  - "2.7"

install:
  - curl -sL https://dl.google.com/dl/cloudsdk/channels/rapid/google-cloud-sdk.tar.gz | tar xfz - -C ${HOME}

before_script:
  - source "$HOME/google-cloud-sdk/path.bash.inc"

script: python -m unittest discover -p '*_test.py' "restae"